version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: homely-postgres
    restart: always
    environment:
      POSTGRES_DB: homely_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14789532
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: homely-backend
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: homely_db
      DB_USER: postgres
      DB_PASSWORD: 14789532
      JWT_SECRET: KJDn7TI/5x1Y1H6m/IfEhYpt4qV3FB110tnxN8IVqnU=
    networks:
      - homely-network

volumes:
  postgres_data:

networks:
  homely-network:
