spring.application.name=backend
server.port=8082
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/homely_db
spring.datasource.username=postgres
spring.datasource.password=14789532

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Frontend URL for email verification links
app.frontend.url=https://unparrying-christene-reductively.ngrok-free.dev

# JWT secret - base64 encoded key
app.jwt.secret=KJDn7TI/5x1Y1H6m/IfEhYpt4qV3FB110tnxN8IVqnU=

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Email configuration (Development - using Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=homely.support@gmail.com
spring.mail.password=jpoc fgro xhpd cirn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=dmnsrbaw9
cloudinary.api-key=	512577536858258
cloudinary.api-secret=fsIxwG-7DZtloanZBqBWGbdUZPI

# MQTT configuration (Mosquitto broker)
mqtt.broker.uri=tcp://localhost:1883
mqtt.client.id=homely-backend
mqtt.topic.prefix=home/notifications