spring.application.name=backend
server.port=8082

spring.datasource.url=jdbc:postgresql://db.ecuzqhcyigqultnaqgcn.supabase.co:5432
spring.datasource.username=postgres
spring.datasource.password=5yP8Z%s2+@EznZ/

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging configuration
logging.level.com.homely.auth.security.JwtFilter=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

supabase.url=https://ecuzqhcyigqultnaqgcn.supabase.co
supabase.service-role-key=sb_publishable_D8mqHUerHR6rzVhvHSlsVg_XCfEhnhJ
supabase.bucket=property-videos

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB