// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A platform-agnostic platform-specific options for initializing Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVrXlLkRRiLyXjJxW6JqwJqOZwVZXPAc',
    appId: '1:1234567890:web:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'homely-notifications',
    authDomain: 'homely-notifications.firebaseapp.com',
    databaseURL: 'https://homely-notifications.firebaseio.com',
    storageBucket: 'homely-notifications.appspot.com',
    measurementId: 'G-ABCDEF1234',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVrXlLkRRiLyXjJxW6JqwJqOZwVZXPAc',
    appId: '1:1234567890:android:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'homely-notifications',
    databaseURL: 'https://homely-notifications.firebaseio.com',
    storageBucket: 'homely-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVrXlLkRRiLyXjJxW6JqwJqOZwVZXPAc',
    appId: '1:1234567890:ios:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'homely-notifications',
    databaseURL: 'https://homely-notifications.firebaseio.com',
    storageBucket: 'homely-notifications.appspot.com',
    iosBundleId: 'com.example.homely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVrXlLkRRiLyXjJxW6JqwJqOZwVZXPAc',
    appId: '1:1234567890:macos:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'homely-notifications',
    databaseURL: 'https://homely-notifications.firebaseio.com',
    storageBucket: 'homely-notifications.appspot.com',
    iosBundleId: 'com.example.homely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKVrXlLkRRiLyXjJxW6JqwJqOZwVZXPAc',
    appId: '1:1234567890:windows:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'homely-notifications',
    databaseURL: 'https://homely-notifications.firebaseio.com',
    storageBucket: 'homely-notifications.appspot.com',
  );
}
